#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING


type StatisticsEvent
  timestamp::Int64
  value::Int64
  StatisticsEvent() = (o=new(); fillunset(o); o)
end # type StatisticsEvent

abstract StatisticsServerClientBase
