#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING


module StatisticsServer

using Thrift
import Thrift.process, Thrift.meta, Thrift.distribute




export meta
export StatisticsEvent # struct
export StatisticsServerHandlerProcessor, StatisticsServerHandlerClient, StatisticsServerHandlerClientBase, appendEvent # service StatisticsServerHandler

include("StatisticsServer_constants.jl")
include("StatisticsServer_types.jl")
include("StatisticsServer_impl.jl")  # server methods to be hand coded
include("StatisticsServerHandler.jl")


end # module StatisticsServer
